const PrivacyPolicy = () => {
  return (
    <div className="max-w-3xl mx-auto p-6 pt-8 ">
      <header className="text-center mb-8">
        <h1 className="md:text-3xl md:text-md text-base font-semibold text-gray-800">Privacy Policy</h1>
        <p className="text-gray-500 text-sm">Last updated: January 23, 2025</p>
      </header>

      <section className="mb-6">
        <p className="md:text-lg text-sm text-gray-700 mb-4">
          At <strong>TVT TEXTILES</strong> ("we," "us," or "our"), we are committed to protecting and respecting your privacy.
          This Privacy Policy explains how we collect, use, and disclose your information when you use our services, and outlines
          your privacy rights and how the law protects you.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="md:text-2xl text-lg font-semibold text-gray-800 mb-4">1. Definitions</h2>
        <ul className="list-inside md:text-lg text-sm list-disc text-gray-700">
          <li><strong>Account</strong>: A unique account created for you to access our services.</li>
          <li><strong>Affiliate</strong>: means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority</li>
          <li><strong>Country</strong>: refers to: Tamil Nadu, India.</li>
          <li><strong>Device</strong>: means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
          <li><strong>Service Provider</strong>:  means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
          <li><strong>Third-party Social Media Service </strong>: refers to any website or any social network website through which a User can log in or create an account to use the Service</li>
          <li><strong>Usage Data</strong>:refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
          <li><strong>Website</strong>: refers to stilesagio, accessible from www.stilesagio.com.</li>
          <li><strong>You</strong>You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          <li><strong>Company</strong>: Refers to <strong>TVT TEXTILES</strong>, located at <strong>65, 6th Street, Padmini Gardens, Kangeyam Road, Tirupur - 641604, India</strong>.</li>
          <li><strong>Cookies</strong>: Small files placed on your device to store browsing details.</li>
          <li><strong>Personal Data</strong>: Any information that can be used to identify you.</li>
          <li><strong>Service</strong>: Refers to the <strong>Website</strong> - <a href="http://www.stilesagio.com" className="text-blue-500" target="_blank" rel="noopener noreferrer">www.stilesagio.com</a></li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="md:text-2xl text-lg font-semibold text-gray-800 mb-4">2. Information We Collect</h2>
        <h3 className="md:text-md text-base font-medium text-gray-700 mb-2">Personal Data</h3>
        <p className="text-gray-700 mb-4">We may collect the following personal information:</p>
        <ul className="list-inside md:text-lg text-sm list-disc text-gray-700 mb-4">
          <li>Email address</li>
          <li>Name</li>
          <li>Phone number</li>
          <li>Address (State, Province, ZIP/Postal code, City)</li>
        </ul>

        <h3 className="md:text-md text-base font-medium text-gray-700 mb-2">Usage Data</h3>
        <p className="text-gray-700 mb-4">Data collected automatically such as:</p>
        <ul className="list-inside md:text-lg text-sm list-disc text-gray-700">
          <li>Device information (IP address, browser type)</li>
          <li>Pages visited</li>
          <li>Time spent on pages</li>
          <li>Mobile device details (when accessing via a mobile device)</li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="md:text-2xl text-lg font-semibold text-gray-800 mb-4">3. How We Use Your Information</h2>
        <p className="text-gray-700 mb-4">We may use your personal data for the following purposes:</p>
        <ul className="list-inside md:text-lg text-sm list-disc text-gray-700">
          <li>Providing and maintaining our service, including monitoring usage</li>
          <li>Managing your account for accessing various features</li>
          <li>To contact you about updates, security notices, and promotional offers</li>
          <li>For business transfers in case of mergers or acquisitions</li>
          <li>For analyzing and improving our service and user experience</li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="md:text-2xl text-lg font-semibold text-gray-800 mb-4">4. Sharing Your Information</h2>
        <p className="text-gray-700 mb-4">We may share your personal information in the following situations:</p>
        <ul className="list-inside md:text-lg text-sm list-disc text-gray-700">
          <li>With Service Providers to help us monitor and analyze usage</li>
          <li>For business transfers during mergers or asset sales</li>
          <li>With our affiliates who are required to honor this policy</li>
          <li>With business partners offering services or promotions</li>
          <li>With your consent, we may disclose your data for other purposes</li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="md:text-2xl text-lg font-semibold text-gray-800 mb-4">5. Retention of Your Personal Data</h2>
        <p className="text-gray-700 mb-4">
          We will retain your personal data only for as long as necessary for the purposes outlined in this policy. This data
          will be kept to comply with legal obligations, resolve disputes, and enforce our policies.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="md:text-2xl text-lg font-semibold text-gray-800 mb-4">6. Security of Your Personal Data</h2>
        <p className="text-gray-700 mb-4">
          We strive to use commercially acceptable means to protect your personal data, but we cannot guarantee absolute security.
          Please take precautions when using the service.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="md:text-2xl text-lg font-semibold text-gray-800 mb-4">7. Changes to this Privacy Policy</h2>
        <p className="text-gray-700 mb-4">
          We may update this Privacy Policy from time to time. Any changes will be posted on this page with an updated date.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="md:text-2xl text-lg font-semibold text-gray-800 mb-4">8. Contact Us</h2>
        <p className="text-gray-700 mb-4">
          If you have any questions about this Privacy Policy, feel free to contact us:
        </p>
        <ul className="list-inside md:text-lg text-sm list-disc text-gray-700">
          <li>Email: <a href="mailto:support@stilesagio.com" className="text-blue-500">support@stilesagio.com</a></li>
          <li>Phone: +91 9677966333</li>
          <li>Address: TVT TEXTILES, 65, 6th Street, Padmini Gardens, Kangeyam Road, Tirupur - 641604, India</li>
        </ul>
      </section>
    </div>
  );
};

export default PrivacyPolicy;
